# Bandit configuration for security scanning
exclude_dirs:
  - /tests/
  - /node_modules/
  - /dist/
  - /.venv/

skips:
  # Skip test files
  - B101  # assert_used (common in tests)

tests:
  - B201  # flask_debug_true
  - B601  # paramiko_calls
  - B602  # subprocess_popen_with_shell_equals_true
  - B603  # subprocess_without_shell_equals_true
  - B604  # any_other_function_with_shell_equals_true
  - B605  # start_process_with_a_shell
  - B606  # start_process_with_no_shell
  - B607  # start_process_with_partial_path
  - B608  # hardcoded_sql_expressions
  - B105  # hardcoded_password_string
  - B106  # hardcoded_password_funcarg
  - B107  # hardcoded_password_default

