# Pre-commit hooks to prevent security issues
# Install with: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Check for common security issues
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: ^public/logo\.png$
      - id: detect-private-key
        exclude: ^scripts/check_secrets\.py$
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Detect secrets using detect-secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            \.secrets\.baseline|
            \.env\.example|
            env\.example|
            package-lock\.json|
            \.md$|
            \.log$|
            \.git/|
            node_modules/|
            dist/|
            __pycache__/
          )$

  # Custom secret scanner specific to this project
  - repo: local
    hooks:
      - id: check-supabase-secrets
        name: Check for hardcoded Supabase credentials
        entry: python scripts/check_secrets.py
        language: system
        pass_filenames: false
        always_run: true
