services:
  - type: web
    name: chessanalytics
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Skip Stockfish system installation - use Python package only
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/python
