"""
Mikhail Tal-inspired greeting messages for player's first move.

These are warm, playful, energetic greetings that can be used instantly
instead of waiting for AI generation. They capture Tal's spirit of
encouragement and excitement about chess.
"""

TAL_GREETINGS = [
    "Welcome to the board! The pieces are ready, and so are you. Let's see what magic you create today!",
    "The adventure begins! Every game is a new story waiting to unfold. Enjoy the journey!",
    "Welcome! The board is your canvas, and these pieces are your tools. Let's make this game memorable!",
    "Ah, the pieces are set! Time to weave some chess magic. I can't wait to see what you have in store!",
    "Welcome, friend! The board awaits your creativity. Let's see what brilliant ideas you bring to life!",
    "The game is afoot! Every move is a chance to shine. Show me what you've got!",
    "Welcome to the battlefield! The pieces are ready, and I'm excited to see your strategy unfold!",
    "Here we go! The board is set, and the pieces are calling. Let's make this game one to remember!",
    "Welcome! Every game is a fresh start, a new opportunity. Let's see what you can do!",
    "The pieces are ready, and so am I! Time to create some chess magic together!",
    "Welcome to the board! I can already feel the excitement. Let's make this game special!",
    "Here we are! The board is yours, and the pieces are waiting. Let's see what adventure unfolds!",
    "Welcome, chess warrior! The pieces are set, and the game is calling. Show me your best!",
    "The board is ready, and I'm excited! Every move is a chance to create something beautiful!",
    "Welcome! The pieces are in position, and the game is about to begin. Let's make it count!",
    "Here we go! The board is your playground, and these pieces are your friends. Let's have fun!",
    "Welcome to the game! The pieces are ready, and I'm here to cheer you on. Let's do this!",
    "The adventure starts now! Every move tells a story. I can't wait to see yours unfold!",
    "Welcome, my friend! The board is set, and the pieces are eager. Let's create something amazing!",
    "Here we are! The pieces are ready, and the game is waiting. Time to show what you're made of!",
    "Welcome to the board! Every game is a new beginning. Let's make this one unforgettable!",
    "The pieces are set, and I'm excited! Time to weave some chess magic together!",
    "Welcome! The board is your stage, and these pieces are your actors. Let's put on a great show!",
    "Here we go! The pieces are ready, and the game is calling. Let's see what you can create!",
    "Welcome to the battlefield! The pieces are in position, and I'm ready to watch you shine!",
    "The board is set, and the pieces are waiting! Every move is a chance to show your brilliance!",
    "Welcome, chess enthusiast! The pieces are ready, and I'm here to support you. Let's make it great!",
    "Here we are! The board is yours, and the pieces are eager. Time to create some magic!",
    "Welcome! The pieces are set, and the game is about to begin. I'm excited to see what you do!",
    "The adventure begins! Every move is a step into the unknown. Let's see where it leads!",
    "Welcome to the board! The pieces are ready, and so is the excitement. Let's make this game count!",
    "Here we go! The board is your playground, and these pieces are your tools. Let's have some fun!",
    "Welcome, friend! The pieces are set, and the game is waiting. Time to show your creativity!",
    "The board is ready, and I'm here! Every move is a chance to surprise and delight. Let's do it!",
    "Welcome! The pieces are in position, and the game is calling. Let's create something special!",
    "Here we are! The board is set, and the pieces are eager. Time to weave some chess poetry!",
    "Welcome to the game! The pieces are ready, and I'm excited. Let's see what magic you bring!",
    "The pieces are set, and the adventure begins! Every move is a new chapter. Let's write a good one!",
    "Welcome! The board is yours, and the pieces are waiting. Time to show what you can do!",
    "Here we go! The pieces are ready, and the game is about to start. I'm here to cheer you on!",
    "Welcome to the board! The pieces are set, and the excitement is building. Let's make it memorable!",
    "The board is ready, and so are you! Every move is an opportunity. Let's see what you create!",
    "Welcome, chess player! The pieces are in position, and the game is waiting. Let's make it great!",
    "Here we are! The board is set, and the pieces are eager. Time to create some chess magic!",
    "Welcome! The pieces are ready, and the game is calling. Let's see what brilliant ideas you have!",
    "The adventure starts now! The board is yours, and the pieces are your friends. Let's have fun!",
    "Welcome to the battlefield! The pieces are set, and I'm excited to see your strategy unfold!",
    "Here we go! The board is ready, and the pieces are waiting. Time to show your creativity!",
    "Welcome, my friend! The pieces are in position, and the game is about to begin. Let's make it count!",
    "The board is set, and the pieces are eager! Every move is a chance to shine. Let's do this!",
]
