[build]
builder = "dockerfile"
dockerfilePath = "python/Dockerfile"
# Set build context to root so Dockerfile can access requirements.txt
buildContext = "."

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
