site_name: Chess Analytics Documentation
site_description: Comprehensive documentation for the Chess Analytics platform
site_author: Chess Analytics Team
site_url: https://chess-analytics-docs.example.com

# Repository
repo_name: chess-analytics/chess-analytics
repo_url: https://github.com/chess-analytics/chess-analytics
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - search
  - mermaid2

# Page tree
nav:
  - Home: index.md
  - Daily Reports:
    - 2025-09-17: DAILY/2025-09-17.md
  - API Documentation: API.md
  - Database:
    - Schema: DB/SCHEMA.md
    - Data Dictionary: DB/DATA_DICTIONARY.md
  - Quality:
    - Test Plan: QUALITY/TEST_PLAN.md
  - Operations:
    - Observability: OBSERVABILITY.md
  - Change Management:
    - Changelog: CHANGELOG.md
  - Diagrams:
    - Module Graph (2025-09-17): diagrams/module-graph-2025-09-17.mmd
    - ERD (2025-09-17): diagrams/erd-2025-09-17.mmd

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chess-analytics
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/chess_analytics
  version:
    provider: mike

# Copyright
copyright: Copyright &copy; 2025 Chess Analytics Team

