-- DEPRECATED - This migration created insecure policies
-- This file is superseded by RESTORE_SECURE_RLS_POLICIES.sql
-- DO NOT USE - Kept for historical reference only
--
-- Original migration granted blanket access with USING (true)
-- and gave ALL permissions to anonymous users, which is a critical security vulnerability
--
-- To restore secure RLS policies, run: RESTORE_SECURE_RLS_POLICIES.sql
